// One-off transform: rewrite src/data/results-generated.ts so that result rows
// are stored as compact tuples [rank, team, time] instead of pretty-printed
// {rank, team, time} objects. This shrinks the file ~3x and cuts the JS that
// ships to the browser on the data-driven pages. The public `generatedResults`
// export keeps the exact same runtime shape (Record<year, Record<class, Result[]>>),
// so no consuming code needs to change.
//
// Run with: node scripts/compact_generated.mjs
import { readFileSync, writeFileSync } from "node:fs";

const path = new URL("../src/data/results-generated.ts", import.meta.url);
const src = readFileSync(path, "utf8");

function extractObjectLiteral(text, marker) {
  const start = text.indexOf(marker);
  if (start === -1) throw new Error(`marker not found: ${marker}`);
  const braceStart = text.indexOf("{", start);
  let depth = 0;
  let inStr = false;
  let esc = false;
  for (let i = braceStart; i < text.length; i++) {
    const ch = text[i];
    if (inStr) {
      if (esc) esc = false;
      else if (ch === "\\") esc = true;
      else if (ch === '"') inStr = false;
      continue;
    }
    if (ch === '"') inStr = true;
    else if (ch === "{") depth++;
    else if (ch === "}") {
      depth--;
      if (depth === 0) return text.slice(braceStart, i + 1);
    }
  }
  throw new Error(`unterminated object for marker: ${marker}`);
}

const resultsJson = extractObjectLiteral(src, "export const generatedResults");
const countsJson = extractObjectLiteral(src, "export const generatedResultCounts");

const results = JSON.parse(resultsJson);
const counts = JSON.parse(countsJson);

// Build the compact tuple representation.
const lines = [];
lines.push("// Generated by scripts/fetch_ultimate_results.py from live.ultimate.dk,");
lines.push("// then compacted by scripts/compact_generated.mjs.");
lines.push("// Rows are stored as compact [rank, team, time] tuples; `generatedResults`");
lines.push("// rehydrates them into Result objects at module load so consumers are unchanged.");
lines.push('import type { Result } from "./results-2026";');
lines.push("");
lines.push("type Row = [number, string, string];");
lines.push("");
lines.push("const rows: Record<string, Record<string, Row[]>> = {");
for (const [year, classes] of Object.entries(results)) {
  lines.push(`  ${JSON.stringify(year)}: {`);
  for (const [cls, arr] of Object.entries(classes)) {
    const tuples = arr
      .map((r) => `[${r.rank},${JSON.stringify(r.team)},${JSON.stringify(r.time)}]`)
      .join(",");
    lines.push(`    ${JSON.stringify(cls)}: [${tuples}],`);
  }
  lines.push("  },");
}
lines.push("};");
lines.push("");
lines.push("function hydrate(");
lines.push("  src: Record<string, Record<string, Row[]>>");
lines.push("): Record<number, Record<string, Result[]>> {");
lines.push("  const out: Record<number, Record<string, Result[]>> = {};");
lines.push("  for (const year of Object.keys(src)) {");
lines.push("    const byClass: Record<string, Result[]> = {};");
lines.push("    for (const cls of Object.keys(src[year])) {");
lines.push("      byClass[cls] = src[year][cls].map(([rank, team, time]) => ({ rank, team, time }));");
lines.push("    }");
lines.push("    out[Number(year)] = byClass;");
lines.push("  }");
lines.push("  return out;");
lines.push("}");
lines.push("");
lines.push("export const generatedResults = hydrate(rows);");
lines.push("");
lines.push(`export const generatedResultCounts = ${JSON.stringify(counts, null, 2)} as const;`);
lines.push("");

writeFileSync(path, lines.join("\n"), "utf8");

// Quick sanity report.
let rowCount = 0;
for (const classes of Object.values(results))
  for (const arr of Object.values(classes)) rowCount += arr.length;
console.log(`Rewrote results-generated.ts — ${rowCount} rows across ${Object.keys(results).length} years.`);
